### ISSUE TITLE
cannot access micka metadata from egdigtest01. Error: Missing REQUEST parameter

### ISSUE THREAD

**Issue by geusgarah2** [GeoEra-GIP/Project-Support-WP8#513] opened 2021-04-29 08:33 UTC
url: https://egditest01.geus.dk/egdi/?mapname=garah_preview#baslay=baseMapGEUS&extent=-3266910,-894170,10412750,5755440

![image](https://user-images.githubusercontent.com/74297105/116523142-31636f80-a8d6-11eb-8266-a6ef4a754b2f.png)

**Comment by nmtoken** [comment] 2021-04-29 09:02
Actual request sent is:

> https://egditest01.geus.dk/egdi/proxy.jsp?callup=https://egdi.geology.cz/csw/?request=GetRecords&query=identifier%3D%27607f2500-6960-4c64-a0eb-61ab0a010833%27&format=application/html&MaxRecords=1&StartPosition=1&elementSetname=full&language=eng

gives error:

`<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd">
<ows:Exception exceptionCode="MissingParameterValue" locator="REQUEST">
<ows:ExceptionText>Missing 'REQUEST' parameter</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>`

A request parameter is sent, and the case (spelling) of the parameter name is not important according to the specification.   However,  changing the parameter name to 'REQUEST' still results in the same error.

The request does seem to be missing other required parameters such as 'service=CSW' and version=m.n.o... but not sure if that is the root cause, or something else.

For example 

> https://egdi.geology.cz/csw/?REQUEST=GetCapabilities&SERVICE=CSW&ACCEPTVERSIONS=2.02,3.0.0&

also gives the same error

**Comment by Kramolisova** [comment] 2021-04-29 14:38
I thing problem is on MapViewer side. I think  @Bjarni Pjetursson (bpj@geus.dk) could help with solving this problem. I am not sure if he is in our support team. How can I assigne him or send him this issue as an email. Could you help me? @mh-geus-dk

**Comment by nmtoken** [comment] 2021-04-29 14:42
Incorrect request parameters may be an issue for the mapviewer, but a request sent directly to the MICKA CSW (e.g. the GetCapabilities request) without going through the mapviewer are also returning an error, so there is an issue with MICKA too.

**Comment by Kramolisova** [comment] 2021-04-29 15:03
I thing, we do not have metadata record for this data in EGDI Metada Catalogue (https://egdi.geology.cz/)
I could not fiind any wit this ID: 27607f2500-6960-4c64-a0eb-61ab0a010833.

**Comment by nmtoken** [comment] 2021-04-29 15:23
That may be an issue for the GetRecord request from the EGDI test server, but the error message is surely wrong?  The error should be record not found, not '_Missing 'REQUEST' parameter._  as the request parameter is not missing in the request.

As mentioned sending a valid GetCapabilities request to the https://egdi.geology.cz/csw service gives the same error, so that's nothing to do with any record id.

**Comment by nmtoken** [comment] 2021-04-29 15:41
POSTing a GetCapabilities request is working for me like:

    <?xml version="1.0" standalone="no"?>
    <ns0:GetCapabilities 
        xmlns:ns0="http://www.opengis.net/cat/csw/2.0.2"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
        outputSchema="http://www.opengis.net/cat/csw/2.0.2" 
        outputFormat="application/xml" 
        version="2.0.2" 
        service="CSW" 
        xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd">
    </ns0:GetCapabilities>

**Comment by nmtoken** [comment] 2021-04-29 15:58
A record with the identifier    _607f2500-6960-4c64-a0eb-61ab0a010833_   exists in MICKA and can be returned using a GetRecordById POST request:

    <?xml version="1.0"?>
    <csw:GetRecordById xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
                   service="CSW" version="2.0.2">
        <csw:Id>607f2500-6960-4c64-a0eb-61ab0a010833</csw:Id>
    </csw:GetRecordById>

Note that in the original request _identifier%3D%27607f2500-6960-4c64-a0eb-61ab0a010833%27_ is URL encoded, you need to remove the %3D%27 at the start and the  %27 at the end to get the identifier

**Comment by Kramolisova** [comment] 2021-04-30 08:59
Thanks, I will send this bug to Stepan Kafka (MIcKA) developer.

**Comment by Kramolisova** [comment] 2021-04-30 09:09
And may be is problem that in matadata record is mising item resource locator with URL to Getcapabilities of WMS

![image](https://user-images.githubusercontent.com/46894474/116673853-2d058800-a9a4-11eb-87cc-a717215b6e01.png)

**Comment by Kramolisova** [comment] 2021-05-05 21:40
Bug in EGDI Metadata Catalogue is fixed now, you can close the issue.

**Closed** 2021-05-06 07:10 UTC
Labels: EGDI platform, bug, metadata/MICKA
